apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
      - name: nodejs-sample
        image: kalyan/nodejs-sample:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
